<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/08/19 20:53:01

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=MathZbior',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
